#!/usr/bin/env bash

mkdir -p assets/{svg,png,'png#'}

for i in {0..9}; do
  convert \
    -background none \
    -density 1200 \
    -resize 512x512 \
    "assets/svg/$i.svg" "assets/png#/$i#10.png"
done
